language: java
jdk:
  - oraclejdk8
  - openjdk14
addons:
  apt:
    packages:
      - graphviz
install: "mvn --show-version --errors --batch-mode validate dependency:go-offline"
script: "mvn --show-version --errors --batch-mode clean install site"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - johan.haleby@gmail.com
        - ning.n.zhang@ericsson.com
        
